management:
  DUT: 111
  sysIP: 1.1.1.11

ports:
  - id: 1-2
    encap: null
    type: ge
    vlan: 10
  - id: 1-3
    encap: dot1q
    type: ge
    vlan: 10
  - id: 1-4
    encap: dot1q
    type: ge
    vlan: 10

router_interface:
  - IntName: 2
    IP: 10.111.222.2/30
    port: 1-2
    encap: null
    vlan: 10
    rtrInstance: 1
    ospfArea: 0
    isisLevel: 2
  - IntName: 3
    IP: 10.111.333.2/30
    port: 1-3
    encap: dot1q
    vlan: 10
    rtrInstance: 0
    ospfArea: 2
    isisLevel: 1
  - IntName: 4
    IP: 10.111.444.2/30
    port: 1-4
    encap: dot1q
    vlan: 10
    rtrInstance: 0
    ospfArea: 0
    isisLevel: 2

router_mpls:
  - peerNode: 22
    IntName: 2
    peerSysIP: 2.2.2.22
  - peerNode: 33
    IntName: 3
    peerSysIP: 1.1.1.33
  - peerNode: 44
    IntName: 4
    peerSysIP: 1.1.1.44
