management:
  DUT: 1
  sysIP: 1.1.1.1

ports:
  - id: 1-2
    encap: null
    vlan: 10
  - id: 3-4
    encap: dot1q
    vlan: 10
  - id: 1-3
    encap: dot1q
    vlan: 10

router_interface:
  - IntName: 2
    IP: 10.1.2.2/30
    port: 1-2
    encapNull: True 
    encap: null
    vlan: 10
    rtrInstance: 1
    ospfArea: 1
  - IntName: 3
    IP: 10.1.3.2/30
    port: 3-4
    encap: dot1q
    vlan: 10
    rtrInstance: 0
    ospfArea: 0
  - IntName: 4
    IP: 10.1.4.2/30
    port: 1-3
    encap: dot1q
    vlan: 10
    rtrInstance: 0
    ospfArea: 0

router_mpls:
  - peerNode: 2
    IntName: 2
    peerSysIP: 1.1.1.2
  - peerNode: 3
    IntName: 3
    peerSysIP: 1.1.1.3
  - peerNode: 4
    IntName: 4
    peerSysIP: 1.1.1.4
